{
 "title": "HTTP and TLS Learning",
 "tags": [
  "Learning",
  "Baseline",
  "Traffic Samples"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "label": "BIG-IP", "query": "grafana-admdb-datasource" },
   {
    "name": "vs",
    "query": "{\"list_vs\":1}"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Baseline Confidence",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "{\"vs\":\"$vs\",\"topic\":\"info\", \"metric\":\"learning\",\"columns\":[0]}"
    }
   ]
  },
  {
   "title": "HTTP Samples collected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "{\"vs\":\"$vs\",\"topic\":\"info\", \"metric\":\"learning\",\"columns\":[2]}"
    }
   ]
  },
  {
   "title": "TLS Baseline Confidence",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "{\"vs\":\"$vs\",\"topic\":\"info\", \"metric\":\"ssl_learning\",\"columns\":[0]}"
    }
   ]
  },
  {
   "title": "TLS Samples collected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "{\"vs\":\"$vs\",\"topic\":\"info\", \"metric\":\"ssl_learning\",\"columns\":[2]}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TPS",
     "query": "{\"vs\":\"$vs\",\"topic\":\"sig\", \"metric\":\"tps\",\"columns\":[0]}"
    },
    {
     "alias": "Baseline",
     "query": "{\"vs\":\"$vs\",\"topic\":\"base\", \"metric\":\"tps\",\"columns\":[0]}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Conns",
     "query": "{\"vs\":\"$vs\",\"topic\":\"sig\", \"metric\":\"conns\",\"columns\":[0]}"
    },
    {
     "alias": "BaselineConns",
     "query": "{\"vs\":\"$vs\",\"topic\":\"base\", \"metric\":\"conns\",\"columns\":[0]}"
    }
   ]
  },
  {
   "title": "TLS Hello Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TLS",
     "query": "{\"vs\":\"$vs\",\"topic\":\"sig\", \"metric\":\"ssl_client_hello_msgs\",\"columns\":[0]}"
    },
    {
     "alias": "Baseline",
     "query": "{\"vs\":\"$vs\",\"topic\":\"base\", \"metric\":\"ssl_client_hello_msgs\",\"columns\":[0]}"
    }
   ]
  },
  {
   "title": "HTTP Legitimate Traffic samples",
   "type": "f5-briangann-datatable-panel",
   "description": "HTTP Legitimate Traffic samples",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "{\"table_columns\":[\"#samples\", \"request\"], \"series2table\":\"noTime\", \"vs\":\"$vs\",\"topic\":\"traffic_sample\",\"metric\":\"http.good\",\"columns\":\"*\", \"precision\":\"default\", \"row_transform\":\"http_request_format\"}"
    }
   ]
  },
  {
   "title": "TLS Handshake Samples",
   "type": "f5-briangann-datatable-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "{\"table_columns\":[\"#samples\", \"request\"], \"series2table\":\"noTime\", \"vs\":\"$vs\",\"topic\":\"traffic_sample\",\"metric\":\"ssl.good\",\"columns\":\"*\", \"precision\":\"default\", \"row_transform\":\"ssl_request_format\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "content": "To enable traffic samples run the following command on BIG-IP:<br/><br/>\n\n<code>\ntmsh modify sys db admdb.debug.traffic.sample value enable</code>"
  }
 ]
}